### ISSUE TITLE
support task priority

### ISSUE THREAD

**Issue by jasper-zhang** [alitto/pond#50]
Can pond add a feature to support task priority? Tasks with higher priority are processed first.

**Comment by alitto** [comment]
Hey @jasper-zhang!
Sorry for the very late reply. We don't currently support tasks with different priorities. You could probably implement that using 2 separate pools, one for regular tasks and a dedicated one for high priority tasks.

**Comment by Naatan** [comment]
Another +1 for task priority. Handling this separately adds a lot of complexity that I'd have liked this library to solve.

I don't understand why this was closed? OP was asking for a future enhancement, but the resolution was we don't "currently" support this. Are you saying you don't want to support it?

The point of a priority mechanism is that you can add a task to a queue at a later time that trumps the priority of already added tasks. ie. the priority is NOT first-come first-serve based. This would be pretty difficult to implement on top of pond without essentially making your own implementation altogether.

**Comment by alitto** [comment]
Hey @Naatan,
You are right, I interpreted this issue as a question rather than a feature request. I guess I read it too quickly, apologies for that 🙏 
I would be happy to review a feature proposal in relation to task priority. It would be nice if it includes concrete examples, proposed API changes (method signatures, modifications to existing methods, new semantics, etc.)
In my mind, incorporating the concept of "task priority" involves several changes to the current API and semantics of pond's worker pools, which would need to be addressed. 

However, there's a feature called ["subpools" in v2](https://github.com/alitto/pond?tab=readme-ov-file#subpools-v2) of pond which provides a way to implement something very similar to "task priority" and may be a good fit for some use cases.
Here's an example. Let's say you are invoking a very expensive service from a third-party which has concurrency limited to 10, and you want to implement 2 different priorities: `high` priority, which can use up to 10 slots to call the expensive service, and `low` priority, which can only use up to 2 slots.
```go
// Create a pool with limited concurrency
highPriority := pond.NewPool(10)

// Create a subpool with a fraction of the parent pool's concurrency (20%)
lowPriority := highPriority.NewSubpool(2)

// Function used to route the task to the appropriate pool depending on its priority
func submitTask(task func(), priority Priority) pond.Task {
  switch taskPriority {
    case Priority.High:
      return highPriority.Submit(task)
    case Priority.Low:
      return lowPriority.Submit(task)
  }
}
```
Just to be clear, this is not 100% equivalent to "task priority" since the 20% of capacity allocated to the sub-pool may be shared by high and low priority tasks based on submission FIFO order. The good thing about this approach is you eliminate "starvation" for low priority tasks, which may happen with regular priority-based queues.

Please let me know your thoughts on this and, if you can, i would like to know more about your particular use case 🙂 

Thanks!
